/*
 * Mieszko Mazurek <mimaz@gmx.com> 
 * 2018
 */

#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <dirent.h>
#include <stdlib.h>

#include <sys/stat.h>

#define AUTHOR_MESSAGE \
    "/*\n" \
    " * File auto-generated by putgame GLSL resource precompiler\n" \
    " * Mieszko Mazurek <mimaz@gmx.com>\n" \
    " * 2018\n" \
    " */\n"

#define MAX_FILENAME_LENGTH 64
#define MAX_FILE_COUNT 64
#define MAX_FILE_SIZE 16384


static char summary[MAX_FILE_COUNT][MAX_FILENAME_LENGTH];
static int filecount;


static const char *comname(const char *filename)
{
    static char comn[MAX_FILENAME_LENGTH];
    const char *bg;
    char *ptr;

    bg = strrchr(filename, '/');


    if (bg == NULL)
        bg = filename;


    strcpy(comn, bg);

    ptr = comn;

    while (*ptr)
    {
        if (strchr(".", *ptr))
            *ptr = '_';

        ptr++;
    }


    return comn;
}

static void process(const char *dstdir,
                    const char *filename)
{
    static char filebuff[MAX_FILE_SIZE];

    const char *common; 
    char outname[MAX_FILENAME_LENGTH];
    FILE *input, *output;
    int readno, i, buflen;

    
    common = comname(filename);


    strcpy(outname, dstdir);
    strcat(outname, "/");
    strcat(outname, filename);
    strcat(outname, ".c");


    input = fopen(filename, "r");

    if (input == NULL)
    {
        fprintf(stderr, "cannot open file %s: %s\n", 
                filename, strerror(errno));

        return;
    }


    buflen = 0;
    readno = fread(filebuff + buflen, sizeof(char), 64, input);

    while (readno > 0)
    {
        buflen += readno;

        readno = fread(filebuff + buflen, sizeof(char), 64, input);
    }

    fclose(input);



    output = fopen(outname, "w");

    if (outname == NULL)
    {
        fprintf(stderr, "cannot open file %s: %s\n", 
                outname, strerror(errno));

        return;
    }


    fprintf(output, "%s\n", AUTHOR_MESSAGE);
    fprintf(output, "const char %s[] = {", common);

    for (i = 0; i < buflen; i++)
    {
        if (i % 8 == 0)
            fprintf(output, "\n    ");

        fprintf(output, "0x%02x, ", filebuff[i]);
    }

    fprintf(output, "\n};\n");

    fclose(output);
    printf("written %s\n", outname);


    strcpy(summary[filecount++], common);
}

static void genheader(const char *filename)
{
    FILE *output;
    int i;


    output = fopen(filename, "w");


    if (output == NULL)
    {
        fprintf(stderr, "cannot open file %s: %s\n", 
                filename, strerror(errno));
        return;
    }


    fprintf(output, "%s\n", AUTHOR_MESSAGE);
    fprintf(output, "#ifdef __cplusplus\n"
                    "extern \"C\" {\n"
                    "#endif\n\n");

    for (i = 0; i < filecount; i++)
    {
        fprintf(output, "extern const char *%s;\n\n", summary[i]);
    }

    fprintf(output, "#ifdef __cplusplus\n"
                    "}\n"
                    "#endif\n");

    fclose(output);
}

int main(int argc, char **argv)
{
    const char *destdir, *header, *source;
    int i;

    if (argc < 3)
    {
        printf("usage: precompiler /foo/destination-dir "
               "header.h source1.jpeg source2.txt\n");
        return 1;
    }

    destdir = argv[1];
    header = argv[2];

    for (i = 3; i < argc; i++)
    {
        source = argv[i];

        process(destdir, source);
    }

    genheader(header);

    return 0;
}
